### ISSUE TITLE
node-gyp 编译失败

### ISSUE THREAD

**Issue by guo-yu** [DoubleSpout/ifile#2]
在一个朋友的linode机器上无法安装ifile，是不是对node版本有限制？node-gyp已经更新到0.9.x

错误如下：

```
> node-gyp rebuild

make: Entering directory `/develop/candybbs/node_modules/candy/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
make: Entering directory `/develop/candybbs/node_modules/candy/node_modules/ifile/build'
  CXX(target) Release/obj.target/ifile/src/ifile.o
  CXX(target) Release/obj.target/ifile/src/ifile_class.o
../src/ifile_class.cpp: In static member function ‘static v8::Handle<v8::Value> ifile_class::match(const v8::Arguments&)’:
../src/ifile_class.cpp:276: error: invalid conversion from ‘void (*)(uv_work_t*, int)’ to ‘void (*)(uv_work_t*)’
../src/ifile_class.cpp:276: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, void (*)(uv_work_t*), void (*)(uv_work_t*))’
../src/ifile_class.cpp: In static member function ‘static void ifile_class::worker_callback(uv_work_t*)’:
../src/ifile_class.cpp:287: warning: deprecated conversion from string constant to ‘char*’
../src/ifile_class.cpp:288: warning: deprecated conversion from string constant to ‘char*’
../src/ifile_class.cpp:388: warning: deprecated conversion from string constant to ‘char*’
../src/ifile_class.cpp:514: warning: deprecated conversion from string constant to ‘char*’
../src/ifile_class.cpp:529: warning: comparison between signed and unsigned integer expressions
../src/ifile_class.cpp:564: warning: comparison between signed and unsigned integer expressions
../src/ifile_class.cpp: In static member function ‘static char* ifile_class::tolower2(char*)’:
../src/ifile_class.cpp:769: warning: comparison between signed and unsigned integer expressions
../src/ifile_class.cpp: In static member function ‘static time_t ifile_class::parseLocalDate(char*)’:
../src/ifile_class.cpp:791: warning: format ‘%s’ expects type ‘char*’, but argument 3 has type ‘char (*)[3]’
../src/ifile_class.cpp:791: warning: format ‘%s’ expects type ‘char*’, but argument 5 has type ‘char (*)[3]’
../src/ifile_class.cpp:791: warning: format ‘%s’ expects type ‘char*’, but argument 10 has type ‘char (*)[3]’
../src/ifile_class.cpp: In static member function ‘static void ifile_class::create_etag(long unsigned int, long unsigned int, std::string&)’:
../src/ifile_class.cpp:1031: warning: format ‘%d’ expects type ‘int’, but argument 4 has type ‘long unsigned int’
../src/ifile_class.cpp:1031: warning: format ‘%d’ expects type ‘int’, but argument 4 has type ‘long unsigned int’
../src/ifile_class.cpp:1032: warning: format ‘%d’ expects type ‘int’, but argument 4 has type ‘long unsigned int’
../src/ifile_class.cpp:1032: warning: format ‘%d’ expects type ‘int’, but argument 4 has type ‘long unsigned int’
../src/ifile_class.cpp: At global scope:
../src/ifile_class.cpp:20: warning: ‘ifile::count’ defined but not used
make: *** [Release/obj.target/ifile/src/ifile_class.o] Error 1
make: Leaving directory `/develop/candybbs/node_modules/candy/node_modules/ifile/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Linux 3.9.3-x86-linode52
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /develop/candybbs/node_modules/candy/node_modules/ifile
gyp ERR! node -v v0.8.18
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok
npm ERR! weird error 1
make: Leaving directory `/develop/candybbs/node_modules/candy/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
npm ERR! not ok code 0
```

**Comment by DoubleSpout** [comment]
需要node0.10.x，你更新到0.10.x试试

**Comment by guo-yu** [comment]
好的，麻烦在readme中说明一下node版本要求吧~

**Comment by DoubleSpout** [comment]
嗯，其实在package.json中是有的：
https://github.com/DoubleSpout/ifile/blob/master/package.json#L27
